### PR TITLE
Makes Client class more extensible.

### PR DESCRIPTION
**Pull request by tarekadam**
Not sure why I changed self to SELF... maybe because it was a const.
However, I also changed some self to static because it helps when people want to extend the Client.php class and maybe change the default entities and stuff like that.

### CODE REVIEW

**Comment by tristanjahier** [comment]
Hi @tarekadam!

Can you tell me in which case you consider interesting to extend the Client?
(In the situation where every default module and method is supported, and the lib provides methods to setup and configure custom modules.)

About the `SELF::` part: I don't wish to have upper case `self` references, it looks oldish to me and that's not recommended by PSR standards.

**Comment by tarekadam** [comment]
I switched to this: https://cristianpontes.github.io/zoho-crm-client-php/#getRelatedRecords

**Comment by tristanjahier** [comment]
OK. Do you plan to update your code though? I am OK with the changes except the `SELF::` part.
If you don't want to contribute anymore, then I will close this pull request.

**Comment by tarekadam** [comment]
Sure, happy to correct that.

**Comment by tristanjahier** [comment]
Hi @tarekadam. You took a bit too long to reply, and I wanted to release v0.3 quickly. So I did not merge this PR, but I thought about your request. I made the `Client` class more extensible.

However, I did not replace this: `->format(self::DEFAULT_FORMAT)` with this: `->format(static::DEFAULT_FORMAT)` because the `DEFAULT_FORMAT` cannot (and should not) be changed, because currently only JSON is supported, and I don't even think that I will support XML responses at some point.

You can find v0.3 change log here: https://github.com/tristanjahier/zoho-crm-php/releases/tag/0.3.0

**Pull request closed without merging**
